name: example
description: A simple command-line application to test the dart_twistmoe library.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_twistmoe:
    path: ../

dev_dependencies:
  pedantic: ^1.9.0
