name: dart_twistmoe
description: A simple library to interact with https://twist.moe/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_socket_channel: any
  http: any
  encrypt: ^5.0.0-beta.1
  crypto: any
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^4.0.0
  pedantic: ^1.9.0

# flutter pub run build_runner watch
